# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gian/Projects/projeto-agenda/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 281, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.registerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.registerButton.setAutoFillBackground(False)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout_3.addWidget(self.registerButton, 0, 0, 1, 1)
        self.listButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.listButton.setObjectName("listButton")
        self.gridLayout_3.addWidget(self.listButton, 3, 0, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_3.addWidget(self.updateButton, 1, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_3.addWidget(self.deleteButton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        self.menu_Registrador_de_alunos = QtWidgets.QMenu(self.menubar)
        self.menu_Registrador_de_alunos.setObjectName("menu_Registrador_de_alunos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_Registrador_de_alunos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registerButton.setText(_translate("MainWindow", "Cadastrar aluno"))
        self.listButton.setText(_translate("MainWindow", "Lista de alunos"))
        self.updateButton.setText(_translate("MainWindow", "Atualizar aluno"))
        self.deleteButton.setText(_translate("MainWindow", "Excluir aluno"))
        self.menu_Registrador_de_alunos.setTitle(_translate("MainWindow", " Registrador de alunos"))
