# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gian/Projects/projeto-agenda/userRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from dataBaseConnection import Database
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(313, 174)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(313, 174))
        Dialog.setMaximumSize(QtCore.QSize(313, 174))
        self.saveUserButton = QtWidgets.QPushButton(Dialog)
        self.saveUserButton.setGeometry(QtCore.QRect(230, 140, 81, 26))
        self.saveUserButton.setObjectName("saveUserButton")
        self.saveUserButton.clicked.connect(self.getInputData)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 119))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.userEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.userEmail.setObjectName("userEmail")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.userEmail)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userRegistration = QtWidgets.QLineEdit(self.layoutWidget)
        self.userRegistration.setObjectName("userRegistration")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userRegistration)
        self.userName = QtWidgets.QLineEdit(self.layoutWidget)
        self.userName.setObjectName("userName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userName)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.saveUserButton.setText(_translate("Dialog", "Salvar"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_2.setText(_translate("Dialog", "Matrícula"))
        self.label.setText(_translate("Dialog", "Nome"))

    def getInputData(self):
        name = self.userName.text()
        registration = self.userRegistration.text()
        email = self.userEmail.text()
        self.userEmail.clear()
        self.userRegistration.clear()
        self.userName.clear()
        msg = QMessageBox()
        msg.setText("Usuário cadastrado com sucesso!")
        msg.setInformativeText('Nome: ' + name + '\n' + 'Matrícula: ' + registration + '\n' + 'Email: ' + email)
        msg.setWindowTitle("Sucesso")
        msg.exec()
        self.sendDataToDatabase(name, email, registration)

    def sendDataToDatabase(self, name, email, registration):
        query = f"INSERT INTO agenda (nome, email, matricula) VALUES ('{name}', '{email}', '{registration}')"
        db = Database()
        results = db.execute_query(query)
        print(results)
        db.close()
