# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gian/Projects/projeto-agenda/userUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from dataBaseConnection import Database
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(439, 400))
        Dialog.setMaximumSize(QtCore.QSize(439, 400))
        self.userList = QtWidgets.QTableView(Dialog)
        self.userList.setGeometry(QtCore.QRect(0, 0, 431, 211))
        self.userList.setObjectName("userList")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(200, 230, 231, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.userRegistration = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userRegistration.setObjectName("userRegistration")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userRegistration)
        self.userName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userName.setObjectName("userName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userName)
        self.userId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userId.setObjectName("userId")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userId)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.userEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userEmail.setObjectName("userEmail")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userEmail)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.userUpdateButton = QtWidgets.QPushButton(Dialog)
        self.userUpdateButton.setGeometry(QtCore.QRect(340, 370, 81, 26))
        self.userUpdateButton.setObjectName("userUpdateButton")
        self.userUpdateButton.clicked.connect(self.getInputData)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(160, 210, 271, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID aluno"))
        self.label_2.setText(_translate("Dialog", "Nome"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "Matrícula"))
        self.userUpdateButton.setText(_translate("Dialog", "Salvar"))
        self.label_5.setText(_translate("Dialog", "Ínsira o ID do aluno que deseja modificar"))

    def getInputData(self):
        userId = self.userId.text()
        name = self.userName.text()
        registration = self.userRegistration.text()
        email = self.userEmail.text()
        self.userId.clear()
        self.userEmail.clear()
        self.userRegistration.clear()
        self.userName.clear()
        msg = QMessageBox()
        msg.setText("Usuário atualizado com sucesso!")
        msg.setInformativeText('Nome: ' + name + '\n' + 'Matrícula: ' + registration + '\n' + 'Email: ' + email)
        msg.setWindowTitle("Sucesso")
        msg.exec()
        self.sendDataToDatabase(userId, name, email, registration)

    def sendDataToDatabase(self, userId, name, email, registration):
        query = f"UPDATE agenda SET nome='{name}', email='{email}', matricula='{registration}' WHERE id={userId}"
        db = Database()
        results = db.execute_query(query)
        print(results)
        db.close()