# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gian/Projects/projeto-agenda/userDelete.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from dataBaseConnection import Database
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 323)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(437, 323))
        Dialog.setMaximumSize(QtCore.QSize(437, 323))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(210, 250, 221, 35))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.userId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userId.setObjectName("userId")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userId)
        self.deleteUsertButton = QtWidgets.QPushButton(Dialog)
        self.deleteUsertButton.setGeometry(QtCore.QRect(310, 290, 121, 26))
        self.deleteUsertButton.setObjectName("deleteUsertButton")
        self.userList = QtWidgets.QTableView(Dialog)
        self.userList.setGeometry(QtCore.QRect(0, 0, 431, 241))
        self.userList.setObjectName("userList")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID aluno"))
        self.deleteUsertButton.setText(_translate("Dialog", "Excluir aluno"))

    def getInputData(self):
        userId = self.userId.text()
        self.userId.clear()
        msg = QMessageBox()
        msg.setText("Usuário excluído com sucesso!")
        msg.setInformativeText('ID: ' + userId)
        msg.setWindowTitle("Sucesso")
        msg.exec()
        self.sendDataToDatabase(userId)

    def sendDataToDatabase(self, userId):
        query = f"DELETE FROM agenda WHERE id = {userId}"
        db = Database()
        results = db.execute_query(query)
        print(results)
        db.close()
